name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  bats:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.6.0

      - name: Run bats
        run: bats -r test

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ludeeus/action-shellcheck@master

  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
